# Generated by Django 3.2.8 on 2021-10-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('value', models.FloatField(default=1, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sur_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('h', 'helicopter')], max_length=20)),
                ('experience', models.FloatField(blank=True, null=True)),
                ('birthplace', models.TextField(blank=True, max_length=200, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('growth', models.FloatField(blank=True, max_length=220, null=True)),
                ('weight', models.FloatField(blank=True, max_length=220, null=True)),
                ('position', models.CharField(choices=[('m', 'manager'), ('w', 'worker')], max_length=20)),
                ('hard_skills', models.ManyToManyField(to='slaves.HardSkill')),
                ('soft_skills', models.ManyToManyField(to='slaves.SoftSkill')),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='slaves.slave')),
            ],
        ),
    ]
