# Generated by Django 3.2.8 on 2021-10-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slave',
            name='subordinates',
            field=models.ManyToManyField(related_name='_slaves_slave_subordinates_+', to='slaves.Slave'),
        ),
    ]
