# Generated by Django 3.2.8 on 2021-10-25 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0002_slave_subordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sur_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('h', 'helicopter')], max_length=20)),
                ('experience', models.FloatField(blank=True, null=True)),
                ('birthplace', models.TextField(blank=True, max_length=200, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('growth', models.FloatField(blank=True, max_length=220, null=True)),
                ('weight', models.FloatField(blank=True, max_length=220, null=True)),
                ('position', models.CharField(choices=[('m', 'manager'), ('w', 'worker')], max_length=20)),
                ('hard_skills', models.ManyToManyField(to='slaves.HardSkill')),
                ('soft_skills', models.ManyToManyField(to='slaves.SoftSkill')),
            ],
        ),
        migrations.AlterField(
            model_name='slave',
            name='subordinates',
            field=models.ManyToManyField(blank=True, null=True, related_name='_slaves_slave_subordinates_+', to='slaves.Slave'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='slaves.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='slaves.userinfo')),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='slaves.manager')),
            ],
        ),
    ]
