# Generated by Django 3.2.8 on 2021-10-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0004_auto_20211025_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='hard_skills',
            field=models.ManyToManyField(null=True, to='slaves.HardSkill'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='soft_skills',
            field=models.ManyToManyField(null=True, to='slaves.SoftSkill'),
        ),
    ]
