# Generated by Django 3.2.8 on 2021-10-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0005_auto_20211025_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskill',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='softskill',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
