# Generated by Django 3.2.8 on 2021-10-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0006_auto_20211026_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskill',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='softskill',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
